name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-10.14, macOS-latest]
        swift: ['4.2.4', '5.0', '5.1.3']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: ${{ matrix.swift }}
    - run: swift --version
  publish:
    needs: [build, test]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: tgymnich/publish-github-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
